###post user
POST http://localhost:8000/api/v1/staffs
Content-Type: application/json

{
    "firstName":"sami",
    "lastName":"kharel",
    "phone":787878,
    "email":"abc@gmail.com"
}

###get staff
GET http://localhost:8000/api/v1/staffs
Content-Type: application/json


###post department
POST http://localhost:8000/api/v1/departments
Content-Type: application/json

{
    "name":"Receptionist"
}

###post
POST http://localhost:8000/api/v1/rosters
Content-Type: application/json

{
    "staffName":"sami",
    "startDate":"may 08 202",
    "endDate":"ksdj",
    "startTime":"sjbhjs",
    "endTime":"sdb",
    "department":"jdbj"
}

###getroster
GET http://localhost:8000/api/v1/rosters/rosterByDate
Content-Type: application/json

{
    "department":"Doctor",
    "date":"2024-05-25T07:14:33.886+00:00"
}

